%--------------------------------------------------------------------------
%   Possible status for function 'saveVideo'.
%--------------------------------------------------------------------------
%   AUTHOR: ZHOU Bofan
%   Last modified by ZHOU Bofan APR-10-2015
%--------------------------------------------------------------------------

function Status = getsaveVideoStatus

Status = struct( 'RAW',      int8(0),   ...
                 'CHECKED',  int8(1),   ...
                 'STARTED',  int8(2),   ...
                 'STOPPED',  int8(3),   ...
                 'SAVED',    int8(4),   ...
                 'DONE',     int8(100), ...
                 'ERROR',    int8(99)       );