function setSonicationTimer(hFigure)

DutyOnTimer = timer('TimerFcn',{@DutyOnTimerFcn,hFigure},...
                    'ExecutionMode','singleShot');
DutyOffTimer = timer('TimerFcn',{@DutyOffTimerFcn,hFigure},...
                     'ExecutionMode','singleShot');
CoolingTimer = timer('TimerFcn',{@CoolingTimerFcn,hFigure},...
                     'ExecutionMode','singleShot');

Timer = struct('on',     DutyOnTimer,...
               'off',    DutyOffTimer,...
               'cooling',    CoolingTimer);

setappdata(hFigure,'timer',Timer);