function Param = getTcpipParam

Param = struct('Address',                   '192.168.0.114',...
               'Port',                      5500,...
               'NetworkRole',               'client',...
               'ReadAsyncMode',             'continuous',...
               'InputBufferSize',           2000,...
               'OutputBufferSize',          2000,...
               'Timeout',                   10,...
               'BytesAvailableFcnMode',     'terminator');