function Directive = getProbeDirective

Directive = struct('QUERY',     hex2dec('FB'),...
                   'CHECK',     hex2dec('FD'),...
                   'ERROR',     hex2dec('F3'),...
                   'ANSWER',    hex2dec('F4'),...
                   'ARRIVE',    hex2dec('F5'),...
                   'ANGLE0',    hex2dec('10'),...
                   'ANGLE90',   hex2dec('34'),...
                   'ANGLE180',  hex2dec('58'),...
                   'LEFT',      hex2dec('62'),...
                   'RIGHT',     hex2dec('6E'));