function Status = getProbeStatus

Status = struct('INITIALIZED',  'INITIALIZED',...
                'CHECKED',      'CHECKED',...
                'ROTATING',     'ROTATING',...
                'ARRIVED',      'ARRIVED',...
                'EXCEPTION',    'EXCEPTION');