%--------------------------------------------------------------------------
%   Set the configuration parameters for serial port.
%--------------------------------------------------------------------------
%   AUTHOR: JI Xiang
%   Last modified by JI Xiang APR-05-2015
%--------------------------------------------------------------------------

function param = getSerialParam

param = struct('BAUD',                    9600,...
               'DataBits',                8,...
               'StopBits',                1,...
               'Parity',                  'none',...
               'ReadAsyncMode',           'continuous',...
               'Timeout',                 15,...
               'InputBufferSize',         10240);