%   AUTHOR: JI Xiang
%   Last modified by JI Xiang MAR-25-2015

function Directive = getSerialDirective

Directive = struct('CONNECT',   hex2dec('FC'),...
                   'IDENTIFY',  hex2dec('F7'),...
                   'ANSWER',    hex2dec('F4'),...
                   'ROTATION',  hex2dec('A2'),...
                   'CYCLE',     hex2dec('A5'));